// playwright.config.ts
import { defineConfig } from "@playwright/test";
import 'dotenv/config';

export default defineConfig({
  testDir: "./tests",

  timeout: 90_000,

  reporter: [
    ['html', {
      open: 'on-failure',          // 'never' (CI), 'on-failure', or 'always'
      outputFolder: 'playwright-report' // default is 'playwright-report'
    }],
    ['allure-playwright'],
  ],

  expect: {
    timeout: 20000, // 10 seconds
  },

  fullyParallel: true,
  retries: 0,
  workers: 1,

  use: {
    // Reuse the authenticated session generated by global-setup
    storageState: process.env.SF_STORAGE_STATE ?? "storageState.json",
    baseURL: process.env.SF_MYDOMAIN_HOST,
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
    actionTimeout: 20000, // 20 seconds for all click
    navigationTimeout: 10000,
  },

  projects: [
    { name: 'Chromium', use: { browserName: 'chromium' } },
    // { name: 'Firefox', use: { browserName: 'firefox' } },
    // { name: 'Webkit', use: { browserName: 'webkit' } }
  ],


globalSetup: './fixtures/global-setup.ts',
  // Paranoid: avoid parallel tests hitting setup simultaneously at first run
});